In [7]:
import pandas as pd

df = pd.read_csv('/content/nvidia_gpu_sales_synthetic_2026_RAW.csv')

print("--- 5 BARIS PERTAMA DATA ---")
display(df.head())

print("\n--- INFORMASI STRUKTUR DATA ---")
df.info()

print("\n--- CEK DATA KOSONG (MISSING VALUES) ---")
print(df.isnull().sum())

print("\n--- STATISTIK DESKRIPTIF ---")
display(df.describe())

--- 5 BARIS PERTAMA DATA ---

,sale_id,sale_date,gpu_model,gpu_family,launch_year,region,sales_channel,customer_segment,units_sold,msrp_usd,avg_street_price_usd,price_premium_pct,stock_status,customer_satisfaction_score,warranty_months,bundle_addon,revenue_usd
0,1,2024-01-12,RTX 4090,Consumer Gaming,2022,Asia-Pacific (ex-China),Retail/Etail,Gaming,8,1599,1796.91,12.38,Low Stock,4.0,12,Software Bundle,14375.30
1,2,2024-01-18,RTX 4070 Ti Super,Consumer Gaming,2024,Asia-Pacific (ex-China),System Integrator/OEM,Content Creation,34,799,964.70,20.74,Low Stock,5.0,12,NaN,32799.82
2,3,2024-01-20,RTX 4080 Super,Consumer Gaming,2024,North America,Retail/Etail,Gaming,30,999,1308.25,30.96,Sold Out,4.0,12,NaN,39247.64
3,4,2024-02-05,H100 SXM,Data Center AI,2022,Asia-Pacific (ex-China),Direct Enterprise,Crypto Mining,5,27000,29202.11,8.16,Low Stock,4.5,24,NaN,146010.54
4,5,2024-02-16,H100 SXM,Data Center AI,2022,Europe,Cloud Provider,Crypto Mining,9,27000,27778.73,2.88,In Stock,4.5,36,NaN,250008.56

--- INFORMASI STRUKTUR DATA ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   sale_id                      7000 non-null   int64
 1   sale_date                    7000 non-null   object
 2   gpu_model                    7000 non-null   object
 3   gpu_family                   7000 non-null   object
 4   launch_year                  7000 non-null   int64
 5   region                       7000 non-null   object
 6   sales_channel                7000 non-null   object
 7   customer_segment             7000 non-null   object
 8   units_sold                   7000 non-null   int64
 9   msrp_usd                     7000 non-null   int64
 10  avg_street_price_usd         7000 non-null   float64
 11  price_premium_pct            7000 non-null   float64
 12  stock_status                 7000 non-null   object
 13  customer_satisfaction_score  7000 non-null   float64
 14  warranty_months              7000 non-null   int64
 15  bundle_addon                 3159 non-null   object
 16  revenue_usd                  7000 non-null   float64
dtypes: float64(4), int64(5), object(8)
memory usage: 929.8+ KB

--- CEK DATA KOSONG (MISSING VALUES) ---
sale_id                           0
sale_date                         0
gpu_model                         0
gpu_family                        0
launch_year                       0
region                            0
sales_channel                     0
customer_segment                  0
units_sold                        0
msrp_usd                          0
avg_street_price_usd              0
price_premium_pct                 0
stock_status                      0
customer_satisfaction_score       0
warranty_months                   0
bundle_addon                   3841
revenue_usd                       0
dtype: int64

--- STATISTIK DESKRIPTIF ---

,sale_id,launch_year,units_sold,msrp_usd,avg_street_price_usd,price_premium_pct,customer_satisfaction_score,warranty_months,revenue_usd
count,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7.000000e+03
mean,3500.500000,2024.264429,21.674143,5212.903857,6042.141264,15.010536,4.428286,19.753714,5.658006e+04
std,2020.870275,1.100049,12.928136,11056.780783,12976.951044,14.348016,0.608437,8.637874,9.996269e+04
min,1.000000,2020.000000,1.000000,549.000000,549.050000,0.000000,1.500000,12.000000,1.393130e+03
25%,1750.750000,2024.000000,12.000000,749.000000,805.090000,4.560000,4.000000,12.000000,1.555133e+04
50%,3500.500000,2025.000000,20.000000,999.000000,1048.015000,8.850000,4.500000,24.000000,2.534293e+04
75%,5250.250000,2025.000000,29.000000,1599.000000,2002.570000,21.352500,5.000000,24.000000,4.670657e+04
max,7000.000000,2025.000000,104.000000,42000.000000,82364.480000,98.460000,5.000000,36.000000,1.225726e+06

In [10]:
df['bundle_addon'] = df['bundle_addon'].fillna('Standalone')


df['sale_date'] = pd.to_datetime(df['sale_date'])

print("--- CEK ULANG MISSING VALUES ---")
print(df.isnull().sum())

print("\n--- CEK ULANG TIPE DATA ---")
print(df.dtypes)

--- CEK ULANG MISSING VALUES ---
sale_id                        0
sale_date                      0
gpu_model                      0
gpu_family                     0
launch_year                    0
region                         0
sales_channel                  0
customer_segment               0
units_sold                     0
msrp_usd                       0
avg_street_price_usd           0
price_premium_pct              0
stock_status                   0
customer_satisfaction_score    0
warranty_months                0
bundle_addon                   0
revenue_usd                    0
scalping_status                0
dtype: int64

--- CEK ULANG TIPE DATA ---
sale_id                                 int64
sale_date                      datetime64[ns]
gpu_model                              object
gpu_family                             object
launch_year                             int64
region                                 object
sales_channel                          object
customer_segment                       object
units_sold                              int64
msrp_usd                                int64
avg_street_price_usd                  float64
price_premium_pct                     float64
stock_status                           object
customer_satisfaction_score           float64
warranty_months                         int64
bundle_addon                           object
revenue_usd                           float64
scalping_status                        object
dtype: object

In [11]:
def categorize_premium(pct):
    if pct <= 5.0:
        return 'Normal MSRP'
    elif pct <= 20.0:
        return 'Slight Premium'
    else:
        return 'Heavy Scalping'

df['scalping_status'] = df['price_premium_pct'].apply(categorize_premium)
print()
display(df[['gpu_model', 'price_premium_pct', 'scalping_status']].head())

           gpu_model  price_premium_pct scalping_status
0           RTX 4090              12.38  Slight Premium
1  RTX 4070 Ti Super              20.74  Heavy Scalping
2     RTX 4080 Super              30.96  Heavy Scalping
3           H100 SXM               8.16  Slight Premium
4           H100 SXM               2.88     Normal MSRP

In [12]:
print("--- 5 BARIS PERTAMA DATA ---")
display(df.head(10))

--- 5 BARIS PERTAMA DATA ---

,sale_id,sale_date,gpu_model,gpu_family,launch_year,region,sales_channel,customer_segment,units_sold,msrp_usd,avg_street_price_usd,price_premium_pct,stock_status,customer_satisfaction_score,warranty_months,bundle_addon,revenue_usd,scalping_status
0,1,2024-01-12,RTX 4090,Consumer Gaming,2022,Asia-Pacific (ex-China),Retail/Etail,Gaming,8,1599,1796.91,12.38,Low Stock,4.0,12,Software Bundle,14375.30,Slight Premium
1,2,2024-01-18,RTX 4070 Ti Super,Consumer Gaming,2024,Asia-Pacific (ex-China),System Integrator/OEM,Content Creation,34,799,964.70,20.74,Low Stock,5.0,12,Standalone,32799.82,Heavy Scalping
2,3,2024-01-20,RTX 4080 Super,Consumer Gaming,2024,North America,Retail/Etail,Gaming,30,999,1308.25,30.96,Sold Out,4.0,12,Standalone,39247.64,Heavy Scalping
3,4,2024-02-05,H100 SXM,Data Center AI,2022,Asia-Pacific (ex-China),Direct Enterprise,Crypto Mining,5,27000,29202.11,8.16,Low Stock,4.5,24,Standalone,146010.54,Slight Premium
4,5,2024-02-16,H100 SXM,Data Center AI,2022,Europe,Cloud Provider,Crypto Mining,9,27000,27778.73,2.88,In Stock,4.5,36,Standalone,250008.56,Normal MSRP
5,6,2024-02-21,RTX 4080 Super,Consumer Gaming,2024,Asia-Pacific (ex-China),Retail/Etail,Gaming,8,999,1129.64,13.08,Low Stock,4.5,12,Extended Warranty,9037.13,Slight Premium
6,7,2024-02-21,RTX 4070 Ti Super,Consumer Gaming,2024,North America,System Integrator/OEM,Gaming,21,799,807.64,1.08,In Stock,5.0,12,Extended Warranty,16960.51,Normal MSRP
7,8,2024-02-22,RTX 4070 Ti Super,Consumer Gaming,2024,China,Retail/Etail,Gaming,16,799,963.95,20.64,Low Stock,3.0,24,Software Bundle,15423.23,Heavy Scalping
8,9,2024-02-22,RTX 4090,Consumer Gaming,2022,Asia-Pacific (ex-China),Retail/Etail,Gaming,21,1599,1608.58,0.60,In Stock,4.5,24,Standalone,33780.23,Normal MSRP
9,10,2024-02-25,H100 SXM,Data Center AI,2022,North America,Direct Enterprise,Hyperscale Datacenter,7,27000,42442.55,57.19,Sold Out,4.0,24,Standalone,297097.88,Heavy Scalping

In [13]:
df.to_csv('nvidia_gpu_sales.csv', index=False)
print()